rg_name  = "rg-todo-aks-prod"
location = "Central India"
vnet_name   = "vnet-todo-prod"
vnet_cidr   = ["10.0.0.0/16"]
subnet_name = "aks-subnet"
subnet_cidr = ["10.0.1.0/24"]
acr_name   = "todoprodacr123"
aks_name   = "todo-aks-prod"
dns_prefix = "todoaks"
law_name   = "todo-log-prod"
sku    = "PerGB2018"
acr_sku = "Basic"
node_count = 1
vm_size   = "Standard_DS2_v2"
network_plugin = "azure"
service_cidr   = "10.1.0.0/16"
    dns_ip = "10.1.0.10"